-- SQL Schema for Bite Instruments Products Table
-- You can run this directly in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    steel_type TEXT,
    size TEXT,
    description TEXT,
    features TEXT[],
    image_url TEXT,
    images TEXT[],
    price TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON public.products
    FOR SELECT USING (true);

-- Quotes table for export requests
CREATE TABLE IF NOT EXISTS public.quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NOT NULL,
    country TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    notes TEXT,
    items JSONB NOT NULL,
    total_amount DECIMAL(10,2),
    status TEXT DEFAULT 'pending'
);

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert access" ON public.quotes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated read access" ON public.quotes FOR SELECT USING (auth.role() = 'authenticated');
